name: 'Generate Assets'
on:
  schedule:
    - cron: '30 0,12 * * *' # Runs at 00:30 and 12:30, every day

  workflow_dispatch:
    inputs:
      VERSION:
        description: 'Generate assets for a specific version. Leave blank for latest version.'
        type: string
        required: false

permissions:
  contents: write
  actions: read
  checks: write

env:
  MANIFEST_URL: 'https://piston-meta.mojang.com/mc/game/version_manifest_v2.json'

jobs:
  check-version:
    name: 'Check version'
    runs-on: ubuntu-latest
    steps:
      - name: 'Fetch latest Minecraft version'
        id: 'fetch-latest-version'
        if: github.event.inputs.VERSION == ''
        run: |
          LATEST_VERSION=$(curl -L $MANIFEST_URL | jq -r '.latest.snapshot')
          echo "Found latest snapshot: \"$LATEST_VERSION\""
          echo "LATEST_VERSION=$LATEST_VERSION" >> "$GITHUB_OUTPUT"

      - name: 'Checkout repository'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Check for existing version tag'
        id: 'check-for-existing-tag'
        env:
          VERSION: ${{ steps.fetch-latest-version.outputs.LATEST_VERSION || inputs.VERSION }}
        run: |
          if git show-ref --tags --verify --quiet "refs/tags/$VERSION"; then
            echo "Tag \"$VERSION\" already exists. Skipping next jobs."
            echo "TAG_EXISTS=TRUE" >> "$GITHUB_OUTPUT"
          else
            echo "Tag \"$VERSION\" does not exist. Running next jobs."
            echo "TAG_EXISTS=FALSE" >> "$GITHUB_OUTPUT"
          fi

    outputs:
      TAG_EXISTS: ${{ steps.check-for-existing-tag.outputs.TAG_EXISTS }}
      VERSION: ${{ steps.fetch-latest-version.outputs.LATEST_VERSION || inputs.VERSION }}

  generate-new-assets:
    name: 'Generate new assets'
    runs-on: ubuntu-latest
    needs: [check-version]
    if: needs.check-version.outputs.TAG_EXISTS == 'FALSE'
    env:
      VERSION: ${{ needs.check-version.outputs.VERSION }}

    steps:
      - name: Clone Go-Manifest
        uses: actions/checkout@v4
        with:
          repository: MinecraftPlayground/go-manifest
          path: go-manifest

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go-manifest/go.mod

      - name: Install tools
        run: |
          sudo apt-get install rename

      - name: 'Download client.jar'
        run: |
          cd go-manifest
          echo "Downloading client.jar for version \"$VERSION\""
          go run examples/get_client/main.go $VERSION

          rename 's/.*/client.jar/s' client_*.jar

          echo "Saved client.jar to \"go-manifest\""

      - name: 'Extract assets from client.jar'
        run: |
          mkdir -p ./default
          unzip go-manifest/client.jar "pack.png" -d "./default"
          unzip go-manifest/client.jar "assets/*" -d "./default"
          rm -fr go-manifest/client.jar

      - name: Download further assets
        run: |
          echo "Downloading assets for version \"$VERSION\""
          go run -C go-manifest examples/get_all_assets/main.go $VERSION

          echo "Merging assets with thoose from client.jar"
          rsync -vr go-manifest/assets default && rm -fr go-manifest/assets

          echo "moving pack.mcmeta to root"
          mv default/assets/pack.mcmeta default/.

      - name: Extract default resourcepacks
        if: ${{ hashFiles('default/assets/minecraft/resourcepacks/*.zip') != '' }}
        run: |
          for pack in default/assets/minecraft/resourcepacks/*.zip; do
            echo "Extracting resourcepack from $pack"
            mv $pack $pack.tmp
            unzip $pack.tmp -d $pack
            rm $pack.tmp
          done

      - name: 'Upload assets'
        uses: actions/upload-artifact@v4
        with:
          name: 'default'
          path: './default'

    outputs:
      VERSION: ${{ needs.check-version.outputs.VERSION }}

  commit-and-tag-new-assets:
    name: 'Commit and tag new assets'
    runs-on: ubuntu-latest
    needs: [generate-new-assets]
    env:
      VERSION: ${{ needs.generate-new-assets.outputs.VERSION }}

    steps:
      - name: ''
        run: |
          echo "Version \"$VERSION\""

      - name: 'Checkout repository'
        uses: actions/checkout@v4
        with:
          ref: 'generated'

      - name: 'Remove old assets'
        run: |
          git rm -rf --ignore-unmatch "./"

      - name: 'Add new assets'
        uses: actions/download-artifact@v4
        with:
          name: 'default'
          path: './'

      - name: 'Commit and push assets'
        run: |
          echo "Commit Message: \"New assets for version $VERSION\""
          echo "Tag: \"$VERSION\""
          echo "Tag Message: \"Version $VERSION\""

          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -a -m "New assets for version $VERSION" || exit 0
          git tag -a "$VERSION" -m "Version $VERSION"
          git push origin generated --tags
