name: 'Generate status badge'
env:
  BADGE_BRANCH: 'badge'

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        required: true
        
      prefix:
        type: string
        required: true
        
      suffix:
        type: string
        required: true

  workflow_call:
    inputs:
      name:
        type: string
        required: true
        
      prefix:
        type: string
        required: true
        
      suffix:
        type: string
        required: true

jobs:
  generate-badge:
    runs-on: ubuntu-24.04

    steps:
      - name: 'Generate GitHub App token'
        id: 'app-token'
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: 'Configure GIT'
        run: |
          git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
          git config --global user.email '${{ secrets.APP_USER_ID }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'

      - name: 'Checkout repository'
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ env.BADGE_BRANCH }}

      - name: 'Generate Badge'
        id: 'generate-badge'
        uses: loat-dev/action-badge@v1
        with:
          icon: 'tag'
          label-text: ${{ inputs.prefix }}
          state-text: ${{ inputs.suffix }}

      - name: 'Commit and push badge'
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          BADGE_FILE: ${{ inputs.name }}

        run: |
          echo -e '${{ steps.generate-badge.outputs.svg-text }}' > $BADGE_FILE
          
          COMMIT_MESSAGE="Update badge '$BADGE_FILE'"
          
          echo "Commit Message: \"$COMMIT_MESSAGE\""

          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "$COMMIT_MESSAGE"
          fi

          git push origin $BADGE_BRANCH

      

