name: 'Schedule'

on:
  # schedule:
  #   - cron: '30 * * * *' # Runs at 30 minutes past the hour, every day

  workflow_dispatch:
    inputs:
      version:
        type: string
        description: 'Run with a specific version. Leave blank for latest version.'
        required: false

jobs:
  version:
    name: "Version (${{ inputs.version && '\"${{ inputs.version }}\"' || 'latest' }})"
    runs-on: ubuntu-latest
    steps:
      - name: 'Get version'
        id: 'manifest'
        uses: MinecraftPlayground/manifest@main
        with:
          version: ${{ inputs.version || 'latest-snapshot' }}

      - name: 'Using version'
        run: |
          echo 'Using version: ${{ steps.manifest.outputs.version }}'

    
